apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: camunda-app1
spec:
  selector:
    matchLabels:
      app:  camunda-app1
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: camunda-app1
    spec:
      containers:
        - name: camunda-app1
          image: camunda/camunda-bpm-platform:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster